// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Backend.PHP
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class IndexTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"

    var _entityInfo = (EntityInfo)Model;

            
            #line default
            #line hidden
            
            #line 5 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
 var keyName = GetPrimaryKey();
            
            #line default
            #line hidden
            this.Write("@extends(\'layouts.master\')\r\n\r\n@section(\'content\')\r\n\r\n<div class=\"container-fluid " +
                    "form-horizontal\">\r\n <div class=\"col-lg-12\">\r\n    <div class=\"card\">\r\n      <div " +
                    "class=\"card-title\">\r\n        <h4>\r\n          ");
            
            #line 15 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.WordSeperator(TextConverter.PascalCase(_entityInfo.Id))));
            
            #line default
            #line hidden
            this.Write(" - List Form</h4>\r\n        <a class=\"btn btn-primary btn-sm float-right\" href=\"/");
            
            #line 16 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityInfo.Id.ToLower()));
            
            #line default
            #line hidden
            this.Write("/create\">Create New</a>\r\n      </div>\r\n      <div class=\"card-body\">\r\n        <di" +
                    "v class=\"table-responsive\">\r\n          <table class=\"table\">\r\n            <thead" +
                    ">\r\n              <tr>\r\n");
            
            #line 23 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"

    foreach(var property in _entityInfo.AllProperties())
    {

            
            #line default
            #line hidden
            this.Write("                  <th>");
            
            #line 27 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.WordSeperator(TextConverter.PascalCase(property.Id))));
            
            #line default
            #line hidden
            this.Write("</th>\r\n");
            
            #line 28 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("              </tr>\r\n            </thead>\r\n            <tbody>\r\n            @fore" +
                    "lse ($items as $item)\r\n              <tr>\r\n");
            
            #line 36 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"

      foreach(var property in _entityInfo.AllProperties())
      {

            
            #line default
            #line hidden
            this.Write("                  <td>{{$item->");
            
            #line 40 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(property.Id)));
            
            #line default
            #line hidden
            this.Write("}}</td>\r\n");
            
            #line 41 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"

      }

            
            #line default
            #line hidden
            this.Write("                  <td>\r\n                      <a class=\"btn btn-info btn-sm\" href" +
                    "=\"/");
            
            #line 45 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityInfo.Id.ToLower()));
            
            #line default
            #line hidden
            this.Write("/{{$item->");
            
            #line 45 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            this.Write("}}\">Details</a>\r\n                      <a class=\"btn btn-warning btn-sm\" href=\"/");
            
            #line 46 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityInfo.Id.ToLower()));
            
            #line default
            #line hidden
            this.Write("/{{$item->");
            
            #line 46 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            this.Write("}}/edit\">Edit</a>\r\n                      <a class=\"btn btn-danger btn-sm\" href=\"/" +
                    "");
            
            #line 47 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityInfo.Id.ToLower()));
            
            #line default
            #line hidden
            this.Write("/{{$item->");
            
            #line 47 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyName));
            
            #line default
            #line hidden
            this.Write("}}?showdelete=true\">Delete</a>\r\n                 </td>\r\n              </tr>\r\n    " +
                    "           @empty \r\n                <p>There no <strong>");
            
            #line 51 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.WordSeperator(TextConverter.PascalCase(_entityInfo.Id))));
            
            #line default
            #line hidden
            this.Write("</strong> defined. Click on <strong>Create New</strong> button to create new ");
            
            #line 51 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\IndexTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.WordSeperator(TextConverter.PascalCase(_entityInfo.Id))));
            
            #line default
            #line hidden
            this.Write(".</p>\r\n              @endforelse\r\n            </tbody>\r\n          </table>\r\n     " +
                    "   </div>\r\n      </div>\r\n    </div>\r\n  </div>\r\n </div>\r\n</div>\r\n\r\n@endsection ");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
