// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Backend.PHP
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\ShowTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ShowTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\ShowTemplate.tt"

    var _entityInfo = (EntityInfo)Model;

            
            #line default
            #line hidden
            this.Write("@extends(\'layouts.master\')\r\n\r\n@section(\'content\')\r\n\r\n<div class=\"container-fluid " +
                    "form-horizontal\">\r\n  <div class=\"col-lg-12\">\r\n    <div class=\"card\">\r\n      <div" +
                    " class=\"card-title\">\r\n            <h4>");
            
            #line 13 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\ShowTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.WordSeperator(TextConverter.PascalCase(_entityInfo.Id))));
            
            #line default
            #line hidden
            this.Write(" - Details Form</h4>\r\n      </div>\r\n      <div class=\"card-body\">\r\n");
            
            #line 16 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\ShowTemplate.tt"

    foreach(var property in _entityInfo.AllProperties())
    {
       if(!property.IsKey)
        {

            
            #line default
            #line hidden
            this.Write("        <div class=\"row\">\r\n            <label for=\"");
            
            #line 23 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\ShowTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(property.Id)));
            
            #line default
            #line hidden
            this.Write("\" class = \"col-sm-2 col-form-label\">");
            
            #line 23 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\ShowTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helper.WordSeperator(TextConverter.PascalCase(property.Id))));
            
            #line default
            #line hidden
            this.Write("</label>\r\n            <div class=\"col-sm-10 label-detail\">\r\n                {{$it" +
                    "em->");
            
            #line 25 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\ShowTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(property.Id)));
            
            #line default
            #line hidden
            this.Write("}}\r\n            </div>\r\n        </div>\r\n");
            
            #line 28 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\ShowTemplate.tt"

        }
          }

            
            #line default
            #line hidden
            this.Write("        <div class=\"row form-action\">\r\n           <div class=\"col-sm-10\">\r\n      " +
                    "          <a class=\"btn btn-warning\" href=\"/");
            
            #line 34 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\ShowTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_entityInfo.Id.ToLower()));
            
            #line default
            #line hidden
            this.Write("/{{$item->");
            
            #line 34 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Views\Templates\ShowTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetPrimaryKey()));
            
            #line default
            #line hidden
            this.Write("}}/edit\">Edit</a>\r\n           </div>\r\n      </div>\r\n      </div>\r\n    </div>\r\n  <" +
                    "/div>\r\n</div>\r\n\r\n@endsection ");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
