// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Backend.PHP
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ApiRoutesTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"

    var smartApp = (SmartAppInfo)Model;

            
            #line default
            #line hidden
            this.Write(@"<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the ""api"" middleware group. Enjoy building your API!
|
*/

Route::middleware('auth:api')->get('/user', function (Request $request) {
    return $request->user();
});

");
            
            #line 24 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"

    if(smartApp != null && smartApp.Api != null && smartApp.Api.Count > 0)
    {
        foreach(var api in smartApp.Api)
        {
            if(api.Actions !=null && api.Actions.Count >0)
            {

            
            #line default
            #line hidden
            this.Write("/**\r\n* Api routes for apiController ");
            
            #line 33 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(api.Id)));
            
            #line default
            #line hidden
            
            #line 33 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_controllerSuffix));
            
            #line default
            #line hidden
            this.Write("\r\n*/\r\n");
            
            #line 35 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"

            foreach(var action in api.Actions)
            {

            
            #line default
            #line hidden
            this.Write("Route::");
            
            #line 39 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRestApiMethod(action.Type)));
            
            #line default
            #line hidden
            this.Write("(\'");
            
            #line 39 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Url));
            
            #line default
            #line hidden
            this.Write("\', \'");
            
            #line 39 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(api.Id)));
            
            #line default
            #line hidden
            
            #line 39 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_controllerSuffix));
            
            #line default
            #line hidden
            this.Write("@");
            
            #line 39 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(action.Id)));
            
            #line default
            #line hidden
            this.Write("\');\r\n");
            
            #line 40 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"

            }

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 44 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Routes\Templates\ApiRoutesTemplate.tt"

         }
        }
    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
