// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Backend.PHP
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.TextTemplating;
    using Mobioos.Scaffold.Generators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ApiControllersTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<?php\r\n\r\nnamespace App\\Http\\ApiControllers;\r\n\r\nuse Illuminate\\Http\\Request;\r\nuse " +
                    "App\\Http\\Requests;\r\nuse App\\Http\\Controllers\\Controller;\r\nuse App\\ViewModels\\;\r\n" +
                    "\r\n/**\r\n* ");
            
            #line 12 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_apiInfo.Description));
            
            #line default
            #line hidden
            this.Write("\r\n*/\r\nclass ");
            
            #line 14 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_apiInfo.Id));
            
            #line default
            #line hidden
            this.Write(" extends Controller\r\n{\r\n");
            
            #line 16 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

    foreach(var action in _apiInfo.Actions)
    {

            
            #line default
            #line hidden
            this.Write("     /**\r\n     * Description of api action\r\n");
            
            #line 22 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

    foreach(var parameter in action.Parameters)
    {

            
            #line default
            #line hidden
            this.Write("     * @param  ");
            
            #line 26 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(PHPType(parameter.Type)));
            
            #line default
            #line hidden
            this.Write("  $");
            
            #line 26 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(parameter.Id)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 27 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("     * @return Response\r\n     */\r\n");
            
            #line 32 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

    if(action.Parameters !=null && action.Parameters.Count>0)
    {

            
            #line default
            #line hidden
            this.Write("     public function ");
            
            #line 36 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(action.Id)));
            
            #line default
            #line hidden
            this.Write("\r\n     (\r\n");
            
            #line 38 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

		int count = action.Parameters.Count -1;
        int counter = 0;
      foreach(var parameter in action.Parameters)
       {
		   if(counter == count)
		   {

            
            #line default
            #line hidden
            this.Write("        $");
            
            #line 46 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(parameter.Id)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 47 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

		}else{

            
            #line default
            #line hidden
            this.Write("\t\t$");
            
            #line 50 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(parameter.Id)));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 51 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

		}
		counter++;
       }

            
            #line default
            #line hidden
            this.Write("     )\r\n");
            
            #line 57 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

    }else{

            
            #line default
            #line hidden
            this.Write("     public function ");
            
            #line 60 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.CamelCase(action.Id)));
            
            #line default
            #line hidden
            this.Write("()\r\n");
            
            #line 61 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

    }

            
            #line default
            #line hidden
            
            #line 64 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

    if(action.ReturnType != null)
    {

            
            #line default
            #line hidden
            this.Write("    : ");
            
            #line 68 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.ReturnType.Id));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 69 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

    }
    else
    {

            
            #line default
            #line hidden
            
            #line 74 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("    {\r\n\r\n    }\r\n\r\n");
            
            #line 81 "D:\Working\Mobioos\Generators\PHP\PHPGeneratorLaravel1\PHPGeneratorLaravel1\GeneratorProject\Platforms\Backend\PHP\Controllers\ApiControllers\Templates\ApiControllersTemplate.tt"

    }

            
            #line default
            #line hidden
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
