// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Backend.PHP
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\ComposerJsonTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ComposerJsonTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\ComposerJsonTemplate.tt"

    var model = (SmartAppInfo) Model;

            
            #line default
            #line hidden
            this.Write("{\r\n    \"name\": \"");
            
            #line 6 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\ComposerJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Id.ToLower()));
            
            #line default
            #line hidden
            this.Write("\",\r\n    \"description\": \"");
            
            #line 7 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\ComposerJsonTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.Description));
            
            #line default
            #line hidden
            this.Write("\",\r\n    \"keywords\": [\"framework\", \"laravel\"],\r\n    \"license\": \"MIT\",\r\n    \"type\":" +
                    " \"project\",\r\n    \"require\": {\r\n        \"php\": \"^7.1.3\",\r\n        \"fideloper/prox" +
                    "y\": \"^4.0\",\r\n        \"laracasts/flash\": \"^3.0\",\r\n        \"laravel/framework\": \"5" +
                    ".6.*\",\r\n        \"laravel/tinker\": \"^1.0\",\r\n        \"laravelcollective/html\": \"^5" +
                    ".6\"\r\n    },\r\n    \"require-dev\": {\r\n        \"filp/whoops\": \"^2.0\",\r\n        \"fzan" +
                    "inotto/faker\": \"^1.4\",\r\n        \"mockery/mockery\": \"^1.0\",\r\n        \"nunomaduro/" +
                    "collision\": \"^2.0\",\r\n        \"phpunit/phpunit\": \"^7.0\"\r\n    },\r\n    \"autoload\": " +
                    "{\r\n        \"classmap\": [\r\n            \"database/seeds\",\r\n            \"database/f" +
                    "actories\"\r\n        ],\r\n        \"psr-4\": {\r\n            \"App\\\\\": \"app/\"\r\n        " +
                    "}\r\n    },\r\n    \"autoload-dev\": {\r\n        \"psr-4\": {\r\n            \"Tests\\\\\": \"te" +
                    "sts/\"\r\n        }\r\n    },\r\n    \"extra\": {\r\n        \"laravel\": {\r\n            \"don" +
                    "t-discover\": [\r\n            ]\r\n        }\r\n    },\r\n    \"scripts\": {\r\n        \"pos" +
                    "t-root-package-install\": [\r\n            \"@php -r \\\"file_exists(\'.env\') || copy(\'" +
                    ".env.example\', \'.env\');\\\"\"\r\n        ],\r\n        \"post-create-project-cmd\": [\r\n  " +
                    "          \"@php artisan key:generate\"\r\n        ],\r\n        \"post-autoload-dump\":" +
                    " [\r\n            \"Illuminate\\\\Foundation\\\\ComposerScripts::postAutoloadDump\",\r\n  " +
                    "          \"@php artisan package:discover\"\r\n        ]\r\n    },\r\n    \"config\": {\r\n " +
                    "       \"preferred-install\": \"dist\",\r\n        \"sort-packages\": true,\r\n        \"op" +
                    "timize-autoloader\": true\r\n    },\r\n    \"minimum-stability\": \"dev\",\r\n    \"prefer-s" +
                    "table\": true\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
