// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Backend.PHP
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.BaseGenerators.TextTemplating;
    using Mobioos.Scaffold.BaseGenerators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\ConfigAppTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ConfigAppTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Application Name
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to place the application's name in a notification or
    | any other location as required by the application or its packages.
    |
    */

    'name' => env('APP_NAME', '");
            
            #line 17 "D:\Working\Mobioos\Generators new changes\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\ConfigAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write("\'),\r\n\r\n    /*\r\n    |-------------------------------------------------------------" +
                    "-------------\r\n    | Application Environment\r\n    |-----------------------------" +
                    "---------------------------------------------\r\n    |\r\n    | This value determine" +
                    "s the \"environment\" your application is currently\r\n    | running in. This may de" +
                    "termine how you prefer to configure various\r\n    | services your application uti" +
                    "lizes. Set this in your \".env\" file.\r\n    |\r\n    */\r\n\r\n    \'env\' => env(\'APP_ENV" +
                    "\', \'production\'),\r\n\r\n    /*\r\n    |----------------------------------------------" +
                    "----------------------------\r\n    | Application Debug Mode\r\n    |---------------" +
                    "-----------------------------------------------------------\r\n    |\r\n    | When y" +
                    "our application is in debug mode, detailed error messages with\r\n    | stack trac" +
                    "es will be shown on every error that occurs within your\r\n    | application. If d" +
                    "isabled, a simple generic error page is shown.\r\n    |\r\n    */\r\n\r\n    \'debug\' => " +
                    "env(\'APP_DEBUG\', false),\r\n\r\n    /*\r\n    |---------------------------------------" +
                    "-----------------------------------\r\n    | Application URL\r\n    |---------------" +
                    "-----------------------------------------------------------\r\n    |\r\n    | This U" +
                    "RL is used by the console to properly generate URLs when using\r\n    | the Artisa" +
                    "n command line tool. You should set this to the root of\r\n    | your application " +
                    "so that it is used when running Artisan tasks.\r\n    |\r\n    */\r\n\r\n    \'url\' => en" +
                    "v(\'APP_URL\', \'http://localhost\'),\r\n\r\n    /*\r\n    |------------------------------" +
                    "--------------------------------------------\r\n    | Application Timezone\r\n    |-" +
                    "-------------------------------------------------------------------------\r\n    |" +
                    "\r\n    | Here you may specify the default timezone for your application, which\r\n " +
                    "   | will be used by the PHP date and date-time functions. We have gone\r\n    | a" +
                    "head and set this to a sensible default for you out of the box.\r\n    |\r\n    */\r\n" +
                    "\r\n    \'timezone\' => \'UTC\',\r\n\r\n    /*\r\n    |-------------------------------------" +
                    "-------------------------------------\r\n    | Application Locale Configuration\r\n " +
                    "   |--------------------------------------------------------------------------\r\n" +
                    "    |\r\n    | The application locale determines the default locale that will be u" +
                    "sed\r\n    | by the translation service provider. You are free to set this value\r\n" +
                    "    | to any of the locales which will be supported by the application.\r\n    |\r\n" +
                    "    */\r\n\r\n    \'locale\' => \'en\',\r\n\r\n    /*\r\n    |--------------------------------" +
                    "------------------------------------------\r\n    | Application Fallback Locale\r\n " +
                    "   |--------------------------------------------------------------------------\r\n" +
                    "    |\r\n    | The fallback locale determines the locale to use when the current o" +
                    "ne\r\n    | is not available. You may change the value to correspond to any of\r\n  " +
                    "  | the language folders that are provided through your application.\r\n    |\r\n   " +
                    " */\r\n\r\n    \'fallback_locale\' => \'en\',\r\n\r\n    /*\r\n    |--------------------------" +
                    "------------------------------------------------\r\n    | Encryption Key\r\n    |---" +
                    "-----------------------------------------------------------------------\r\n    |\r\n" +
                    "    | This key is used by the Illuminate encrypter service and should be set\r\n  " +
                    "  | to a random, 32 character string, otherwise these encrypted strings\r\n    | w" +
                    "ill not be safe. Please do this before deploying an application!\r\n    |\r\n    */\r" +
                    "\n\r\n    \'key\' => env(\'APP_KEY\'),\r\n\r\n    \'cipher\' => \'AES-256-CBC\',\r\n\r\n    /*\r\n   " +
                    " |--------------------------------------------------------------------------\r\n  " +
                    "  | Autoloaded Service Providers\r\n    |-----------------------------------------" +
                    "---------------------------------\r\n    |\r\n    | The service providers listed her" +
                    "e will be automatically loaded on the\r\n    | request to your application. Feel f" +
                    "ree to add your own services to\r\n    | this array to grant expanded functionalit" +
                    "y to your applications.\r\n    |\r\n    */\r\n\r\n    \'providers\' => [\r\n\r\n        /*\r\n  " +
                    "       * Laravel Framework Service Providers...\r\n         */\r\n        Illuminate" +
                    "\\Auth\\AuthServiceProvider::class,\r\n        Illuminate\\Broadcasting\\BroadcastServ" +
                    "iceProvider::class,\r\n        Illuminate\\Bus\\BusServiceProvider::class,\r\n        " +
                    "Illuminate\\Cache\\CacheServiceProvider::class,\r\n        Illuminate\\Foundation\\Pro" +
                    "viders\\ConsoleSupportServiceProvider::class,\r\n        Illuminate\\Cookie\\CookieSe" +
                    "rviceProvider::class,\r\n        Illuminate\\Database\\DatabaseServiceProvider::clas" +
                    "s,\r\n        Illuminate\\Encryption\\EncryptionServiceProvider::class,\r\n        Ill" +
                    "uminate\\Filesystem\\FilesystemServiceProvider::class,\r\n        Illuminate\\Foundat" +
                    "ion\\Providers\\FoundationServiceProvider::class,\r\n        Illuminate\\Hashing\\Hash" +
                    "ServiceProvider::class,\r\n        Illuminate\\Mail\\MailServiceProvider::class,\r\n  " +
                    "      Illuminate\\Notifications\\NotificationServiceProvider::class,\r\n        Illu" +
                    "minate\\Pagination\\PaginationServiceProvider::class,\r\n        Illuminate\\Pipeline" +
                    "\\PipelineServiceProvider::class,\r\n        Illuminate\\Queue\\QueueServiceProvider:" +
                    ":class,\r\n        Illuminate\\Redis\\RedisServiceProvider::class,\r\n        Illumina" +
                    "te\\Auth\\Passwords\\PasswordResetServiceProvider::class,\r\n        Illuminate\\Sessi" +
                    "on\\SessionServiceProvider::class,\r\n        Illuminate\\Translation\\TranslationSer" +
                    "viceProvider::class,\r\n        Illuminate\\Validation\\ValidationServiceProvider::c" +
                    "lass,\r\n        Illuminate\\View\\ViewServiceProvider::class,\r\n\r\n        Collective" +
                    "\\Html\\HtmlServiceProvider::class,\r\n        Laracasts\\Flash\\FlashServiceProvider:" +
                    ":class,\r\n\r\n        /*\r\n         * Package Service Providers...\r\n         */\r\n\r\n " +
                    "       /*\r\n         * Application Service Providers...\r\n         */\r\n        App" +
                    "\\Providers\\AppServiceProvider::class,\r\n        App\\Providers\\AuthServiceProvider" +
                    "::class,\r\n        // App\\Providers\\BroadcastServiceProvider::class,\r\n        App" +
                    "\\Providers\\EventServiceProvider::class,\r\n        App\\Providers\\RouteServiceProvi" +
                    "der::class,\r\n\r\n    ],\r\n\r\n    /*\r\n    |------------------------------------------" +
                    "--------------------------------\r\n    | Class Aliases\r\n    |--------------------" +
                    "------------------------------------------------------\r\n    |\r\n    | This array " +
                    "of class aliases will be registered when this application\r\n    | is started. How" +
                    "ever, feel free to register as many as you wish as\r\n    | the aliases are \"lazy\"" +
                    " loaded so they don\'t hinder performance.\r\n    |\r\n    */\r\n\r\n    \'aliases\' => [\r\n" +
                    "\r\n        \'App\' => Illuminate\\Support\\Facades\\App::class,\r\n        \'Artisan\' => " +
                    "Illuminate\\Support\\Facades\\Artisan::class,\r\n        \'Auth\' => Illuminate\\Support" +
                    "\\Facades\\Auth::class,\r\n        \'Blade\' => Illuminate\\Support\\Facades\\Blade::clas" +
                    "s,\r\n        \'Broadcast\' => Illuminate\\Support\\Facades\\Broadcast::class,\r\n       " +
                    " \'Bus\' => Illuminate\\Support\\Facades\\Bus::class,\r\n        \'Cache\' => Illuminate\\" +
                    "Support\\Facades\\Cache::class,\r\n        \'Config\' => Illuminate\\Support\\Facades\\Co" +
                    "nfig::class,\r\n        \'Cookie\' => Illuminate\\Support\\Facades\\Cookie::class,\r\n   " +
                    "     \'Crypt\' => Illuminate\\Support\\Facades\\Crypt::class,\r\n        \'DB\' => Illumi" +
                    "nate\\Support\\Facades\\DB::class,\r\n        \'Eloquent\' => Illuminate\\Database\\Eloqu" +
                    "ent\\Model::class,\r\n        \'Event\' => Illuminate\\Support\\Facades\\Event::class,\r\n" +
                    "        \'File\' => Illuminate\\Support\\Facades\\File::class,\r\n        \'Gate\' => Ill" +
                    "uminate\\Support\\Facades\\Gate::class,\r\n        \'Hash\' => Illuminate\\Support\\Facad" +
                    "es\\Hash::class,\r\n        \'Lang\' => Illuminate\\Support\\Facades\\Lang::class,\r\n    " +
                    "    \'Log\' => Illuminate\\Support\\Facades\\Log::class,\r\n        \'Mail\' => Illuminat" +
                    "e\\Support\\Facades\\Mail::class,\r\n        \'Notification\' => Illuminate\\Support\\Fac" +
                    "ades\\Notification::class,\r\n        \'Password\' => Illuminate\\Support\\Facades\\Pass" +
                    "word::class,\r\n        \'Queue\' => Illuminate\\Support\\Facades\\Queue::class,\r\n     " +
                    "   \'Redirect\' => Illuminate\\Support\\Facades\\Redirect::class,\r\n        \'Redis\' =>" +
                    " Illuminate\\Support\\Facades\\Redis::class,\r\n        \'Request\' => Illuminate\\Suppo" +
                    "rt\\Facades\\Request::class,\r\n        \'Response\' => Illuminate\\Support\\Facades\\Res" +
                    "ponse::class,\r\n        \'Route\' => Illuminate\\Support\\Facades\\Route::class,\r\n    " +
                    "    \'Schema\' => Illuminate\\Support\\Facades\\Schema::class,\r\n        \'Session\' => " +
                    "Illuminate\\Support\\Facades\\Session::class,\r\n        \'Storage\' => Illuminate\\Supp" +
                    "ort\\Facades\\Storage::class,\r\n        \'URL\' => Illuminate\\Support\\Facades\\URL::cl" +
                    "ass,\r\n        \'Validator\' => Illuminate\\Support\\Facades\\Validator::class,\r\n     " +
                    "   \'View\' => Illuminate\\Support\\Facades\\View::class,\r\n        \'Form\' => Collecti" +
                    "ve\\Html\\FormFacade::class,\r\n        \'Html\' => Collective\\Html\\HtmlFacade::class," +
                    "\r\n\r\n    ],\r\n\r\n];\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
