// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Backend.PHP
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.TextTemplating;
    using Mobioos.Scaffold.Generators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\01 Working\01 RedFabriq\01 working\generators\php\generator\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\ConfigAppTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ConfigAppTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Application Name
    |--------------------------------------------------------------------------
    |
    | This value is the name of your application. This value is used when the
    | framework needs to place the application's name in a notification or
    | any other location as required by the application or its packages.
    |
    */

    'name' => env('APP_NAME', '");
            
            #line 2 "D:\01 Working\01 RedFabriq\01 working\generators\php\generator\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\ConfigAppTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ApplicationId));
            
            #line default
            #line hidden
            this.Write("\'),\n\n    /*\n    |----------------------------------------------------------------" +
                    "----------\n    | Application Environment\n    |----------------------------------" +
                    "----------------------------------------\n    |\n    | This value determines the \"" +
                    "environment\" your application is currently\n    | running in. This may determine " +
                    "how you prefer to configure various\n    | services your application utilizes. Se" +
                    "t this in your \".env\" file.\n    |\n    */\n\n    \'env\' => env(\'APP_ENV\', \'productio" +
                    "n\'),\n\n    /*\n    |--------------------------------------------------------------" +
                    "------------\n    | Application Debug Mode\n    |---------------------------------" +
                    "-----------------------------------------\n    |\n    | When your application is i" +
                    "n debug mode, detailed error messages with\n    | stack traces will be shown on e" +
                    "very error that occurs within your\n    | application. If disabled, a simple gene" +
                    "ric error page is shown.\n    |\n    */\n\n    \'debug\' => env(\'APP_DEBUG\', false),\n\n" +
                    "    /*\n    |--------------------------------------------------------------------" +
                    "------\n    | Application URL\n    |----------------------------------------------" +
                    "----------------------------\n    |\n    | This URL is used by the console to prop" +
                    "erly generate URLs when using\n    | the Artisan command line tool. You should se" +
                    "t this to the root of\n    | your application so that it is used when running Art" +
                    "isan tasks.\n    |\n    */\n\n    \'url\' => env(\'APP_URL\', \'http://localhost\'),\n\n    " +
                    "/*\n    |------------------------------------------------------------------------" +
                    "--\n    | Application Timezone\n    |---------------------------------------------" +
                    "-----------------------------\n    |\n    | Here you may specify the default timez" +
                    "one for your application, which\n    | will be used by the PHP date and date-time" +
                    " functions. We have gone\n    | ahead and set this to a sensible default for you " +
                    "out of the box.\n    |\n    */\n\n    \'timezone\' => \'UTC\',\n\n    /*\n    |------------" +
                    "--------------------------------------------------------------\n    | Application" +
                    " Locale Configuration\n    |-----------------------------------------------------" +
                    "---------------------\n    |\n    | The application locale determines the default " +
                    "locale that will be used\n    | by the translation service provider. You are free" +
                    " to set this value\n    | to any of the locales which will be supported by the ap" +
                    "plication.\n    |\n    */\n\n    \'locale\' => \'en\',\n\n    /*\n    |--------------------" +
                    "------------------------------------------------------\n    | Application Fallbac" +
                    "k Locale\n    |------------------------------------------------------------------" +
                    "--------\n    |\n    | The fallback locale determines the locale to use when the c" +
                    "urrent one\n    | is not available. You may change the value to correspond to any" +
                    " of\n    | the language folders that are provided through your application.\n    |" +
                    "\n    */\n\n    \'fallback_locale\' => \'en\',\n\n    /*\n    |---------------------------" +
                    "-----------------------------------------------\n    | Encryption Key\n    |------" +
                    "--------------------------------------------------------------------\n    |\n    |" +
                    " This key is used by the Illuminate encrypter service and should be set\n    | to" +
                    " a random, 32 character string, otherwise these encrypted strings\n    | will not" +
                    " be safe. Please do this before deploying an application!\n    |\n    */\n\n    \'key" +
                    "\' => env(\'APP_KEY\'),\n\n    \'cipher\' => \'AES-256-CBC\',\n\n    /*\n    |--------------" +
                    "------------------------------------------------------------\n    | Autoloaded Se" +
                    "rvice Providers\n    |-----------------------------------------------------------" +
                    "---------------\n    |\n    | The service providers listed here will be automatica" +
                    "lly loaded on the\n    | request to your application. Feel free to add your own s" +
                    "ervices to\n    | this array to grant expanded functionality to your applications" +
                    ".\n    |\n    */\n\n    \'providers\' => [\n\n        /*\n         * Laravel Framework Se" +
                    "rvice Providers...\n         */\n        Illuminate\\Auth\\AuthServiceProvider::clas" +
                    "s,\n        Illuminate\\Broadcasting\\BroadcastServiceProvider::class,\n        Illu" +
                    "minate\\Bus\\BusServiceProvider::class,\n        Illuminate\\Cache\\CacheServiceProvi" +
                    "der::class,\n        Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvide" +
                    "r::class,\n        Illuminate\\Cookie\\CookieServiceProvider::class,\n        Illumi" +
                    "nate\\Database\\DatabaseServiceProvider::class,\n        Illuminate\\Encryption\\Encr" +
                    "yptionServiceProvider::class,\n        Illuminate\\Filesystem\\FilesystemServicePro" +
                    "vider::class,\n        Illuminate\\Foundation\\Providers\\FoundationServiceProvider:" +
                    ":class,\n        Illuminate\\Hashing\\HashServiceProvider::class,\n        Illuminat" +
                    "e\\Mail\\MailServiceProvider::class,\n        Illuminate\\Notifications\\Notification" +
                    "ServiceProvider::class,\n        Illuminate\\Pagination\\PaginationServiceProvider:" +
                    ":class,\n        Illuminate\\Pipeline\\PipelineServiceProvider::class,\n        Illu" +
                    "minate\\Queue\\QueueServiceProvider::class,\n        Illuminate\\Redis\\RedisServiceP" +
                    "rovider::class,\n        Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider::" +
                    "class,\n        Illuminate\\Session\\SessionServiceProvider::class,\n        Illumin" +
                    "ate\\Translation\\TranslationServiceProvider::class,\n        Illuminate\\Validation" +
                    "\\ValidationServiceProvider::class,\n        Illuminate\\View\\ViewServiceProvider::" +
                    "class,\n\n        Collective\\Html\\HtmlServiceProvider::class,\n        Laracasts\\Fl" +
                    "ash\\FlashServiceProvider::class,\n\n        /*\n         * Package Service Provider" +
                    "s...\n         */\n\n        /*\n         * Application Service Providers...\n       " +
                    "  */\n        App\\Providers\\AppServiceProvider::class,\n        App\\Providers\\Auth" +
                    "ServiceProvider::class,\n        // App\\Providers\\BroadcastServiceProvider::class" +
                    ",\n        App\\Providers\\EventServiceProvider::class,\n        App\\Providers\\Route" +
                    "ServiceProvider::class,\n\n    ],\n\n    /*\n    |-----------------------------------" +
                    "---------------------------------------\n    | Class Aliases\n    |---------------" +
                    "-----------------------------------------------------------\n    |\n    | This arr" +
                    "ay of class aliases will be registered when this application\n    | is started. H" +
                    "owever, feel free to register as many as you wish as\n    | the aliases are \"lazy" +
                    "\" loaded so they don\'t hinder performance.\n    |\n    */\n\n    \'aliases\' => [\n\n   " +
                    "     \'App\' => Illuminate\\Support\\Facades\\App::class,\n        \'Artisan\' => Illumi" +
                    "nate\\Support\\Facades\\Artisan::class,\n        \'Auth\' => Illuminate\\Support\\Facade" +
                    "s\\Auth::class,\n        \'Blade\' => Illuminate\\Support\\Facades\\Blade::class,\n     " +
                    "   \'Broadcast\' => Illuminate\\Support\\Facades\\Broadcast::class,\n        \'Bus\' => " +
                    "Illuminate\\Support\\Facades\\Bus::class,\n        \'Cache\' => Illuminate\\Support\\Fac" +
                    "ades\\Cache::class,\n        \'Config\' => Illuminate\\Support\\Facades\\Config::class," +
                    "\n        \'Cookie\' => Illuminate\\Support\\Facades\\Cookie::class,\n        \'Crypt\' =" +
                    "> Illuminate\\Support\\Facades\\Crypt::class,\n        \'DB\' => Illuminate\\Support\\Fa" +
                    "cades\\DB::class,\n        \'Eloquent\' => Illuminate\\Database\\Eloquent\\Model::class" +
                    ",\n        \'Event\' => Illuminate\\Support\\Facades\\Event::class,\n        \'File\' => " +
                    "Illuminate\\Support\\Facades\\File::class,\n        \'Gate\' => Illuminate\\Support\\Fac" +
                    "ades\\Gate::class,\n        \'Hash\' => Illuminate\\Support\\Facades\\Hash::class,\n    " +
                    "    \'Lang\' => Illuminate\\Support\\Facades\\Lang::class,\n        \'Log\' => Illuminat" +
                    "e\\Support\\Facades\\Log::class,\n        \'Mail\' => Illuminate\\Support\\Facades\\Mail:" +
                    ":class,\n        \'Notification\' => Illuminate\\Support\\Facades\\Notification::class" +
                    ",\n        \'Password\' => Illuminate\\Support\\Facades\\Password::class,\n        \'Que" +
                    "ue\' => Illuminate\\Support\\Facades\\Queue::class,\n        \'Redirect\' => Illuminate" +
                    "\\Support\\Facades\\Redirect::class,\n        \'Redis\' => Illuminate\\Support\\Facades\\" +
                    "Redis::class,\n        \'Request\' => Illuminate\\Support\\Facades\\Request::class,\n  " +
                    "      \'Response\' => Illuminate\\Support\\Facades\\Response::class,\n        \'Route\' " +
                    "=> Illuminate\\Support\\Facades\\Route::class,\n        \'Schema\' => Illuminate\\Suppo" +
                    "rt\\Facades\\Schema::class,\n        \'Session\' => Illuminate\\Support\\Facades\\Sessio" +
                    "n::class,\n        \'Storage\' => Illuminate\\Support\\Facades\\Storage::class,\n      " +
                    "  \'URL\' => Illuminate\\Support\\Facades\\URL::class,\n        \'Validator\' => Illumin" +
                    "ate\\Support\\Facades\\Validator::class,\n        \'View\' => Illuminate\\Support\\Facad" +
                    "es\\View::class,\n        \'Form\' => Collective\\Html\\FormFacade::class,\r\n        \'H" +
                    "tml\' => Collective\\Html\\HtmlFacade::class,\n\n    ],\n\n];\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
