// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GeneratorProject.Platforms.Backend.PHP
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Mobioos.Scaffold.TextTemplating;
    using Mobioos.Scaffold.Generators.Helpers;
    using Mobioos.Foundation.Jade.Models;
    using Mobioos.Foundation.Jade.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\01 Working\01 RedFabriq\01 working\generators\php\generator\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\EnvTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class EnvTemplate : TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\nAPP_NAME=");
            
            #line 1 "D:\01 Working\01 RedFabriq\01 working\generators\php\generator\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\EnvTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TextConverter.PascalCase(ApplicationId)));
            
            #line default
            #line hidden
            this.Write("\r\nAPP_ENV=local\r\nAPP_KEY=base64:");
            
            #line 3 "D:\01 Working\01 RedFabriq\01 working\generators\php\generator\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\EnvTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_appKey));
            
            #line default
            #line hidden
            this.Write("\r\nAPP_DEBUG=true\r\nAPP_URL=http://localhost\r\n\r\nLOG_CHANNEL=stack\r\n\r\nDB_CONNECTION=" +
                    "");
            
            #line 9 "D:\01 Working\01 RedFabriq\01 working\generators\php\generator\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\EnvTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_databaseType));
            
            #line default
            #line hidden
            this.Write("\r\nDB_HOST=");
            
            #line 10 "D:\01 Working\01 RedFabriq\01 working\generators\php\generator\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\EnvTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_databaseHost));
            
            #line default
            #line hidden
            this.Write("\r\nDB_PORT=");
            
            #line 11 "D:\01 Working\01 RedFabriq\01 working\generators\php\generator\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\EnvTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_databasePort));
            
            #line default
            #line hidden
            this.Write("\r\nDB_DATABASE=");
            
            #line 12 "D:\01 Working\01 RedFabriq\01 working\generators\php\generator\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\EnvTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_databaseName));
            
            #line default
            #line hidden
            this.Write("\r\nDB_USERNAME=");
            
            #line 13 "D:\01 Working\01 RedFabriq\01 working\generators\php\generator\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\EnvTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_databaseUsername));
            
            #line default
            #line hidden
            this.Write("\r\nDB_PASSWORD=");
            
            #line 14 "D:\01 Working\01 RedFabriq\01 working\generators\php\generator\PHP-LARAVEL\PHPGeneratorLaravel\GeneratorProject\Platforms\Backend\PHP\Common\Templates\EnvTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_databasePassword));
            
            #line default
            #line hidden
            this.Write(@"

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=log
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY=""${PUSHER_APP_KEY}""
MIX_PUSHER_APP_CLUSTER=""${PUSHER_APP_CLUSTER}""
");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
